---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spbak8s-svc
  labels:
    app: {{ .Release.Name }}-spbak8s
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-spbak8s
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spbak8s-svc-act
  labels:
    app: {{ .Release.Name }}-spbak8s
    type: {{ .Values.labelactuator }}
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-spbak8s
---