---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spbak8s-svc-ext
  labels:
    app: {{ .Release.Name }}-spbak8s
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.ext_port }}
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-spbak8s
  externalTrafficPolicy: Local
---