replicas: 1
### Credenciales repositorio repo-cred
imagepullsecret:
### Imagenes 
image: royalwang/spring-boot-admin-k8s:2.3.12.RELEASE_Hoxton.SR12_2.2.2
### Politica descarga de imagenes
imagepullpolicy: IfNotPresent
### Puertos
ext_port: "8080"
### Recursos 
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
### Test
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 1
  successThreshold: 1
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 1
  successThreshold: 1
### Autoscaling
mem:
  minreplicas: 1
  maxreplicas: 1
  avgutilization: 80
cpu:
  minreplicas: 1
  maxreplicas: 1
  avgutilization: 80
### Configurations SPBA
serviceaccountname: "spbak8s-service-account"
rolename: "spbak8s-role"
rolebindingname: "spbak8s-role-binding"
labelactuator: "actuator"
spbausername: "springbootadmin"
spbuserpassw: "password"
allnamespaces: "true"

